#!/bin/bash -e

if [ -z "$AWS_ACCESS_KEY_ID" ] ; then
    echo "AWS_ACCESS_KEY_ID not specified"
    exit 1
fi

if [ -z "$AWS_SECRET_ACCESS_KEY" ] ; then
    echo "AWS_SECRET_ACCESS_KEY not specified"
    exit 1
fi

if [ -z "$BUCKET" ] ; then
    echo "BUCKET not specified"
    exit 1
fi

if [ -z "$FILE" ] ; then
    echo "FILE not specified"
    exit 1
fi

echo "Restoring $FILE"
aws s3 cp $BUCKET/$FILE.tar.gz /backup/bck.tar.gz 

gzip -d /backup/bck.tar.gz

tar xf /backup/bck.tar -C /backup

rm -rf /backup/bck.tar
mv /backup/backup/**/* /backup
rm -rf /backup/backup

rm -rf /data/*
innobackupex --defaults-file=/app/my.cnf --copy-back /backup
